version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws s3 sync dist/ s3://bucket-front-dev-kryvobok
      - aws cloudfront create-invalidation --distribution-id E3M1SKJSPQ0MKC --paths "/*"

artifacts:
  files:
    - '**/*'

