version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - export VUE_APP_BASE_SERVERLESS_URL="https://7dbokj7zsf.execute-api.eu-west-1.amazonaws.com/main"
      - echo $VUE_APP_BASE_SERVERLESS_URL
      - export VUE_APP_BASE_DOCKER_URL="https://docker_api_kryvobok_${ENV}.kozub.dev"
      - echo $VUE_APP_BASE_DOCKER_URL
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://$S3_CONTENT_BUCKET_FRONT
      - aws cloudfront create-invalidation --distribution-id $CL_FRONT_DIST_ID --paths "/*"

artifacts:
  files:
    - '**/*'
